[package]
name = "magic_migrate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1", features = ["derive"]}

[dev-dependencies]
chrono = { version = "0.4", features = ["serde"] }
toml = "0.8"
